using System.Collections.ObjectModel;

namespace PM5Control.Core.Bwm;

public sealed record BwmCommandDefinition(string Group, ushort Code, string Name, string Description, bool ExposedByCurrentFirmware);

public static class BwmCommandCatalog
{
    public static IReadOnlyList<BwmCommandDefinition> All { get; } = Build();

    public static IReadOnlyList<BwmCommandDefinition> ForGroup(string group) => All.Where(x => x.Group.Equals(group, StringComparison.OrdinalIgnoreCase)).ToArray();

    private static IReadOnlyList<BwmCommandDefinition> Build()
    {
        var list = new List<BwmCommandDefinition>();
        Add(list, "System", 1000, new[]
        {
            "GET_VERSION_INFO", "GET_DEVICE_MODEL", "GET_SYS_FREE_HEAP", "GET_SYS_TIMESTAMP", "GET_APP_COMPILE_DATETIME",
            "SET_SYS_TIMESTAMP", "GET_SYS_TIME_ZONE", "SET_SYS_TIME_ZONE", "GET_SYS_BASE_MAC_ADDR",
            "GET_SYS_UART_CMD_BAUD_RATE", "GET_SYS_UART_CMD_MAX_BAUD_RATE", "SET_SYS_UART_CMD_BAUD_RATE", "GET_SYS_NVS_STATS",
            "RESTORE_TO_FACTORY_SETTINGS", "SET_LOG_UART_FORWARD_ENABLE", "GET_LOG_UART_FORWARD_ENABLE", "SET_LOG_LEVEL",
            "GET_LOG_LEVEL", "GET_SYS_READY_STATUS"
        });
        Add(list, "OTA", 1800, new[] { "OTA_BEGIN", "OTA_WRITE", "OTA_END", "REBOOT" });
        Add(list, "Wi-Fi", 2000, new[]
        {
            "SET_TO_WIFI_DISABLE_MODE", "SET_TO_WIFI_FORWARD_MODE", "SET_TO_WIFI_SCAN_MODE", "START_WIFI_SCAN_TASK", "STOP_WIFI_SCAN_TASK",
            "SET_WIFI_SCAN_CONFIG", "GET_WIFI_SCAN_STATUS", "SET_WIFI_CFG_COUNTRY", "GET_WIFI_CFG_COUNTRY", "SET_WIFI_CFG_TX_PWR",
            "GET_WIFI_CFG_TX_PWR", "SET_WIFI_CFG_INACTIVE_TIME", "GET_WIFI_CFG_INACTIVE_TIME", "SET_WIFI_CFG_DHCP", "GET_WIFI_CFG_DHCP",
            "SET_WIFI_CFG_PROTOCOL", "GET_WIFI_CFG_PROTOCOL", "SET_WIFI_CFG_MAC_ADDR", "GET_WIFI_CFG_MAC_ADDR", "SET_WIFI_CFG_IP_ADDR",
            "GET_WIFI_CFG_IP_ADDR", "SET_WIFI_CFG_HOST_NAME", "GET_WIFI_CFG_HOST_NAME", "SET_WIFI_CONNECT_CFG_SSID", "GET_WIFI_CONNECT_CFG_SSID",
            "SET_WIFI_CONNECT_CFG_PASSWORD", "GET_WIFI_CONNECT_CFG_PASSWORD", "SET_WIFI_CONNECT_CFG_BSSID", "GET_WIFI_CONNECT_CFG_BSSID",
            "SET_WIFI_CONNECT_CFG_AUTHMODE", "GET_WIFI_CONNECT_CFG_AUTHMODE", "SET_WIFI_CONNECT_CFG_LISTEN_INTERVAL", "GET_WIFI_CONNECT_CFG_LISTEN_INTERVAL",
            "SET_WIFI_CONNECT_CFG_SCAN_MODE", "GET_WIFI_CONNECT_CFG_SCAN_MODE", "SET_WIFI_CONNECT_CFG_PMF", "GET_WIFI_CONNECT_CFG_PMF",
            "SET_WIFI_CONNECT_CFG_RECONNECT_INTERVAL", "GET_WIFI_CONNECT_CFG_RECONNECT_INTERVAL", "SET_WIFI_SNTP_ENABLE", "GET_WIFI_SNTP_ENABLE",
            "SET_WIFI_SNTP_SERVER", "GET_WIFI_SNTP_SERVER", "SET_WIFI_SNTP_INTERVAL", "GET_WIFI_SNTP_INTERVAL", "START_WIFI_SNTP",
            "STOP_WIFI_SNTP", "GET_WIFI_SNTP_SYNC_STATUS", "START_WIFI_CONNECT_TASK", "STOP_WIFI_CONNECT_TASK", "GET_WIFI_CONNECT_STATUS",
            "WAIT_FOR_WIFI_CONNECT_TASK"
        });
        Add(list, "TCP Server", 2200, new[]
        {
            "GET_TCP_SERVER_STATUS", "START_TCP_SERVER", "STOP_TCP_SERVER", "SET_TCP_SERVER_IP_PROTOCOL", "GET_TCP_SERVER_IP_PROTOCOL",
            "SET_TCP_SERVER_PORT", "GET_TCP_SERVER_PORT", "SET_TCP_SERVER_SO_LINGER", "GET_TCP_SERVER_SO_LINGER", "SET_TCP_SERVER_NODELAY",
            "GET_TCP_SERVER_NODELAY", "SET_TCP_SERVER_SO_SNDTIMEO", "GET_TCP_SERVER_SO_SNDTIMEO", "SET_TCP_SERVER_KEEP_ALIVE", "GET_TCP_SERVER_KEEP_ALIVE"
        });
        Add(list, "TCP Client", 2300, new[]
        {
            "GET_TCP_CLIENT_STATUS", "START_TCP_CLIENT", "STOP_TCP_CLIENT", "SET_TCP_CLIENT_IP_ADDR", "GET_TCP_CLIENT_IP_ADDR",
            "SET_TCP_CLIENT_PORT", "GET_TCP_CLIENT_PORT", "SET_TCP_CLIENT_SO_LINGER", "GET_TCP_CLIENT_SO_LINGER", "SET_TCP_CLIENT_NODELAY",
            "GET_TCP_CLIENT_NODELAY", "SET_TCP_CLIENT_SO_SNDTIMEO", "GET_TCP_CLIENT_SO_SNDTIMEO", "SET_TCP_CLIENT_KEEP_ALIVE", "GET_TCP_CLIENT_KEEP_ALIVE"
        });
        Add(list, "UDP Server", 2400, new[]
        {
            "GET_UDP_SERVER_STATUS", "START_UDP_SERVER", "STOP_UDP_SERVER", "SET_UDP_SERVER_IP_PROTOCOL", "GET_UDP_SERVER_IP_PROTOCOL",
            "SET_UDP_SERVER_PORT", "GET_UDP_SERVER_PORT", "SET_UDP_SERVER_SO_SNDTIMEO", "GET_UDP_SERVER_SO_SNDTIMEO",
            "SET_UDP_SERVER_CLIENT_IP_ADDR", "GET_UDP_SERVER_CLIENT_IP_ADDR", "SET_UDP_SERVER_CLIENT_PORT", "GET_UDP_SERVER_CLIENT_PORT"
        });
        Add(list, "UDP Client", 2500, new[]
        {
            "GET_UDP_CLIENT_STATUS", "START_UDP_CLIENT", "STOP_UDP_CLIENT", "SET_UDP_CLIENT_IP_PROTOCOL", "GET_UDP_CLIENT_IP_PROTOCOL",
            "SET_UDP_CLIENT_LOCAL_PORT", "GET_UDP_CLIENT_LOCAL_PORT", "SET_UDP_CLIENT_SO_SNDTIMEO", "GET_UDP_CLIENT_SO_SNDTIMEO",
            "SET_UDP_CLIENT_SERVER_IP_ADDR", "GET_UDP_CLIENT_SERVER_IP_ADDR", "SET_UDP_CLIENT_SERVER_PORT", "GET_UDP_CLIENT_SERVER_PORT"
        });
        Add(list, "MQTT", 2600, new[]
        {
            "GET_MQTT_CLIENT_STATUS", "START_MQTT_CLIENT", "STOP_MQTT_CLIENT", "SET_MQTT_CLIENT_HOST", "GET_MQTT_CLIENT_HOST",
            "SET_MQTT_CLIENT_PORT", "GET_MQTT_CLIENT_PORT", "SET_MQTT_CLIENT_PATH", "GET_MQTT_CLIENT_PATH", "SET_MQTT_CLIENT_SCHEME",
            "GET_MQTT_CLIENT_SCHEME", "SET_MQTT_CLIENT_SUBSCRIBE_TOPIC", "GET_MQTT_CLIENT_SUBSCRIBE_TOPIC", "SET_MQTT_CLIENT_SUBSCRIBE_QOS",
            "GET_MQTT_CLIENT_SUBSCRIBE_QOS", "SET_MQTT_CLIENT_PUBLISH_TOPIC", "GET_MQTT_CLIENT_PUBLISH_TOPIC", "SET_MQTT_CLIENT_PUBLISH_QOS",
            "GET_MQTT_CLIENT_PUBLISH_QOS", "SET_MQTT_CLIENT_PUBLISH_RETAIN", "GET_MQTT_CLIENT_PUBLISH_RETAIN", "SET_MQTT_CLIENT_CLIENT_ID",
            "GET_MQTT_CLIENT_CLIENT_ID", "SET_MQTT_CLIENT_USERNAME", "GET_MQTT_CLIENT_USERNAME", "SET_MQTT_CLIENT_PASSWORD",
            "GET_MQTT_CLIENT_PASSWORD", "SET_MQTT_CLIENT_KEEP_ALIVE", "GET_MQTT_CLIENT_KEEP_ALIVE", "SET_MQTT_CLIENT_DISABLE_CLEAN_SESSION",
            "GET_MQTT_CLIENT_DISABLE_CLEAN_SESSION", "SET_MQTT_CLIENT_LWT_TOPIC", "GET_MQTT_CLIENT_LWT_TOPIC", "SET_MQTT_CLIENT_LWT_MESSAGE",
            "GET_MQTT_CLIENT_LWT_MESSAGE", "SET_MQTT_CLIENT_LWT_QOS", "GET_MQTT_CLIENT_LWT_QOS", "SET_MQTT_CLIENT_LWT_RETAIN",
            "GET_MQTT_CLIENT_LWT_RETAIN", "ADD_MQTT_CLIENT_ALPN", "DEL_MQTT_CLIENT_ALPN", "GET_MQTT_CLIENT_ALPN",
            "GET_MQTT_CLIENT_ALPN_COUNT", "CLEAR_MQTT_CLIENT_ALPN", "SET_MQTT_CLIENT_SNI_HOST", "GET_MQTT_CLIENT_SNI_HOST",
            "SET_MQTT_CLIENT_CACERT", "GET_MQTT_CLIENT_CACERT", "SET_MQTT_CLIENT_CCERT", "GET_MQTT_CLIENT_CCERT",
            "SET_MQTT_CLIENT_CCKEY", "GET_MQTT_CLIENT_CCKEY", "SET_MQTT_CLIENT_PSK_DATA", "GET_MQTT_CLIENT_PSK_DATA",
            "SET_MQTT_CLIENT_PSK_HINT", "GET_MQTT_CLIENT_PSK_HINT"
        });
        Add(list, "Bluetooth LE", 4000, new[]
        {
            "SET_BLE_ADV_MFG_DATA", "GET_BLE_ADV_MFG_DATA", "SET_BLE_DEVICE_NAME", "GET_BLE_DEVICE_NAME", "SET_BLE_NOTIFY_RETRY_MAX",
            "GET_BLE_NOTIFY_RETRY_MAX", "SET_BLE_DEVICE_ADDR", "GET_BLE_DEVICE_ADDR", "SET_BLE_BONDING_ENABLE", "GET_BLE_BONDING_ENABLE",
            "SET_BLE_BONDING_KEY", "GET_BLE_BONDING_KEY", "GET_BLE_BONDED_DEVICE_NUMS", "GET_BLE_BONDED_DEVICE_ADDR",
            "DEL_BLE_BONDED_DEVICE", "CLEAR_BLE_BONDED", "SET_BLE_BATTERY_LEVEL", "GET_BLE_BATTERY_LEVEL", "SET_BLE_TX_POWER",
            "GET_BLE_TX_POWER", "GET_BLE_SPP_STATUS", "START_BLE_SPP", "STOP_BLE_SPP"
        });
        Add(list, "Forward", 5000, new[] { "SEND_FORWARD_DATA" });
        return new ReadOnlyCollection<BwmCommandDefinition>(list);
    }

    private static void Add(List<BwmCommandDefinition> list, string group, int start, IEnumerable<string> names)
    {
        var code = start;
        foreach (var name in names)
        {
            list.Add(new BwmCommandDefinition(group, checked((ushort)code++), name, Describe(name), true));
        }
    }

    private static string Describe(string name) => name switch
    {
        _ when name.StartsWith("GET_", StringComparison.Ordinal) => "Read value from the BWM firmware.",
        _ when name.StartsWith("SET_", StringComparison.Ordinal) => "Configure a BWM firmware setting.",
        _ when name.StartsWith("START_", StringComparison.Ordinal) => "Start the corresponding BWM service/task.",
        _ when name.StartsWith("STOP_", StringComparison.Ordinal) => "Stop the corresponding BWM service/task.",
        _ => "Command exposed by the current upstream BWM command definition."
    };
}
