using Microsoft.Win32;
using System.Text;
using System.Text.RegularExpressions;
using PM5Control.Core.Connections;
using PM5Control.Core.Protocols.Pm3;

namespace PM5Control.Desktop;

internal sealed class MainForm2 : Form
{
    private const string ClientVersion = "0.6.1";
    private const string BuildCommit = "pending CI";
    private static readonly Color Bg = Color.FromArgb(18,20,24);
    private static readonly Color LogBg = Color.FromArgb(10,12,15);
    private static readonly Color TextColor = Color.FromArgb(226,230,236);
    private static readonly Color Muted = Color.FromArgb(145,153,164);
    private static readonly Color Orange = Color.FromArgb(255,122,24);
    private static readonly Color Green = Color.FromArgb(94,214,130);
    private readonly Label _transport=ValueLabel(),_usb=ValueLabel(),_ble=ValueLabel(),_wifi=ValueLabel(),_device=ValueLabel(),_arm=ValueLabel(),_fpga=ValueLabel(),_bwm=ValueLabel(),_build=ValueLabel();
    private readonly TextBox _consoleLog=new(),_diagLog=new(),_cmdLine=new();
    private readonly ComboBox _command=new();
    private readonly Button _execute=new(),_cancel=new(),_analyze=new();
    private readonly CheckBox _developer=new(),_raw=new(),_timestamps=new();
    private CancellationTokenSource? _cts;
    private string? _port; private bool _busy;

    public MainForm2(){ Text="Proxmark5 Control Center"; StartPosition=FormStartPosition.CenterScreen; MinimumSize=new Size(1000,700); Size=new Size(1180,780); BackColor=Bg; ForeColor=TextColor; Font=new Font("Segoe UI",10F); BuildUi(); RefreshPorts(); Log(_diagLog,$"PM5 Control Center v{ClientVersion} started. Read-only mode: write/reset/flash unavailable."); }

    private void BuildUi(){
        var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=2,BackColor=Bg}; root.RowStyles.Add(new RowStyle(SizeType.Absolute,76)); root.RowStyles.Add(new RowStyle(SizeType.Percent,100)); Controls.Add(root);
        var header=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,BackColor=Bg,Padding=new Padding(18,10,18,8)}; header.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100)); header.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        var title=new Label{Text="PROXMARK5  CONTROL CENTER",AutoSize=true,Font=new Font("Segoe UI Black",18F),ForeColor=Orange}; var sub=new Label{Text=$"Read-only diagnostic client · v{ClientVersion} · {BuildCommit}",AutoSize=true,ForeColor=Muted,Font=new Font("Consolas",9F),Location=new Point(0,38)}; var left=new Panel{Dock=DockStyle.Fill}; left.Controls.Add(title);left.Controls.Add(sub); var ro=new Label{Text="READ-ONLY",AutoSize=true,BackColor=Green,ForeColor=Color.Black,Padding=new Padding(10,5,10,5)}; header.Controls.Add(left);header.Controls.Add(ro);root.Controls.Add(header);
        var tabs=new TabControl{Dock=DockStyle.Fill,BackColor=Bg,ForeColor=TextColor,Padding=new Point(14,6)}; tabs.TabPages.Add(BuildDeviceTab());tabs.TabPages.Add(BuildConsoleTab());tabs.TabPages.Add(BuildDiagnosticsTab());tabs.TabPages.Add(BuildSettingsTab());root.Controls.Add(tabs);
    }
    private TabPage BuildDeviceTab(){ var p=Page("DEVICE"); var g=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=9,Padding=new Padding(20),BackColor=Bg};g.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,230));g.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100)); AddRow(g,0,"Transport",_transport);AddRow(g,1,"USB / Serial",_usb);AddRow(g,2,"Bluetooth / BLE",_ble);AddRow(g,3,"Wi-Fi",_wifi);AddRow(g,4,"Device family",_device);AddRow(g,5,"ARM firmware",_arm);AddRow(g,6,"FPGA",_fpga);AddRow(g,7,"ESP32 / BWM",_bwm);AddRow(g,8,"Client build",_build);_build.Text=$"v{ClientVersion} · {BuildCommit}";p.Controls.Add(g);return p; }
    private TabPage BuildConsoleTab(){ var p=Page("CONSOLE"); var quick=new FlowLayoutPanel{Dock=DockStyle.Top,Height=52,Padding=new Padding(18,10,18,4),BackColor=Bg}; foreach(var x in new[]{("PING","hw ping"),("VERSION","hw version"),("CAPABILITIES","hw capabilities"),("STATUS","hw status")}){var b=new Button{Text=x.Item1,AutoSize=true};b.Click+=async(_,_)=>await ExecuteCommandAsync(x.Item2);quick.Controls.Add(b);}p.Controls.Add(quick);
        var cmd=new FlowLayoutPanel{Dock=DockStyle.Top,Height=48,Padding=new Padding(18,5,18,5),BackColor=Bg};_cmdLine.Width=430;_cmdLine.PlaceholderText="PM5> whitelisted command";_execute.Text="Execute";_cancel.Text="Cancel";_cancel.Enabled=false;_analyze.Text="Connect / analyze";_execute.Click+=async(_,_)=>await ExecuteCommandAsync(_cmdLine.Text.Trim());_cancel.Click+=(_,_)=>CancelCurrent();_analyze.Click+=async(_,_)=>await AnalyzeAsync();cmd.Controls.Add(_cmdLine);cmd.Controls.Add(_execute);cmd.Controls.Add(_cancel);cmd.Controls.Add(_analyze);p.Controls.Add(cmd);
        _command.DropDownStyle=ComboBoxStyle.DropDownList;_command.Width=250;_command.Items.AddRange(new object[]{"hw version","hw status","hw capabilities","hw ping"});_command.SelectedIndex=0;_command.SelectedIndexChanged+=(_,_)=>_cmdLine.Text=_command.Text;cmd.Controls.Add(_command); ConfigureLog(_consoleLog);p.Controls.Add(_consoleLog);return p; }
    private TabPage BuildDiagnosticsTab(){var p=Page("DIAGNOSTICS");var info=new Label{Dock=DockStyle.Top,Height=42,Text="Developer/raw transport view. Interleaved frames, TX/RX, timeout and response matching are shown here.",Padding=new Padding(18,12,18,4),ForeColor=Muted};p.Controls.Add(info);ConfigureLog(_diagLog);p.Controls.Add(_diagLog);return p;}
    private TabPage BuildSettingsTab(){var p=Page("SETTINGS");var g=new TableLayoutPanel{Dock=DockStyle.Top,ColumnCount=2,RowCount=6,Padding=new Padding(24),Height=240,BackColor=Bg};g.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,260));g.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));g.Controls.Add(new Label{Text="COM port",ForeColor=Muted,Dock=DockStyle.Fill},0,0);g.Controls.Add(new Label{Text="Auto-detect (COM3 preferred)",ForeColor=TextColor,Dock=DockStyle.Fill},1,0);g.Controls.Add(new Label{Text="Baudrate",ForeColor=Muted,Dock=DockStyle.Fill},0,1);g.Controls.Add(new Label{Text="460800",ForeColor=TextColor,Dock=DockStyle.Fill},1,1);_developer.Text="Developer mode";_developer.Checked=true;_raw.Text="Show raw frames";_raw.Checked=true;_timestamps.Text="Show timestamps";_timestamps.Checked=true;g.Controls.Add(_developer,0,2);g.Controls.Add(_raw,0,3);g.Controls.Add(_timestamps,0,4);g.Controls.Add(new Label{Text="Safety: READ-ONLY · write/reset/flash disabled",ForeColor=Green,Dock=DockStyle.Fill},1,3);p.Controls.Add(g);return p;}
    private static TabPage Page(string t)=>new(t){BackColor=Bg,ForeColor=Color.White}; private static Label ValueLabel()=>new(){Dock=DockStyle.Fill,Text="UNKNOWN",TextAlign=ContentAlignment.MiddleLeft,Font=new Font("Consolas",10F,FontStyle.Bold),ForeColor=Color.White}; private static void AddRow(TableLayoutPanel g,int r,string n,Label v){g.RowStyles.Add(new RowStyle(SizeType.Percent,100F/9F));g.Controls.Add(new Label{Text=n,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft,ForeColor=Color.FromArgb(145,153,164)},0,r);g.Controls.Add(v,1,r);} private static void ConfigureLog(TextBox b){b.Multiline=true;b.ReadOnly=true;b.ScrollBars=ScrollBars.Vertical;b.Dock=DockStyle.Fill;b.BackColor=LogBg;b.ForeColor=Green;b.Font=new Font("Consolas",9.5F);}
    private async Task AnalyzeAsync(){if(!TryGetPort())return;await RunAsync("Connect / analyze",async t=>{var i=await Pm3ReadOnlyInspector.InspectAsync(t);_transport.Text="USB / Serial ACTIVE";_usb.Text=$"Connected · {_port}";_device.Text=i.Identity.Hardware;_arm.Text=i.Identity.ArmFirmware;_fpga.Text=i.Identity.FpgaFirmware;_bwm.Text=$"PM3 capabilities v{i.Capabilities.SchemaVersion}; {(i.Capabilities.IsRdv4?"RDV4 flag set":"no RDV4 flag")}";_ble.Text="NOT ACTIVE · BLE telemetry not queried";_wifi.Text="NOT ACTIVE · Wi-Fi telemetry not queried";Log(_consoleLog,"Read-only handshake succeeded.");Log(_consoleLog,$"ARM: {i.Identity.ArmFirmware}");Log(_consoleLog,$"FPGA: {i.Identity.FpgaFirmware}");Log(_consoleLog,$"Hardware: {i.Identity.Hardware}");Log(_consoleLog,$"Capabilities schema v{i.Capabilities.SchemaVersion}; known={i.Capabilities.IsKnownSchema}; USB={(i.Capabilities.ViaUsb?"yes":"no")}; BigBuf={i.Capabilities.BigBufferSize} bytes; features={string.Join(", ",i.Capabilities.EnabledFeatures)}.");});}
    private async Task ExecuteCommandAsync(string command){if(string.IsNullOrWhiteSpace(command)){Log(_consoleLog,"Empty command rejected.");return;}command=command.Trim();var allowed=new[]{"hw ping","hw version","hw capabilities","hw status"};if(!allowed.Contains(command,StringComparer.OrdinalIgnoreCase)){Log(_consoleLog,$"Rejected: command is not on the read-only whitelist: {command}");return;}if(!TryGetPort())return;await RunAsync(command,async t=>{switch(command.ToLowerInvariant()){case "hw version":var id=await Pm3ReadOnlyInspector.QueryVersionAsync(t);_device.Text=id.Hardware;_arm.Text=id.ArmFirmware;_fpga.Text=id.FpgaFirmware;Log(_consoleLog,$"ARM: {id.ArmFirmware}");Log(_consoleLog,$"FPGA: {id.FpgaFirmware}");Log(_consoleLog,$"Hardware: {id.Hardware}");break;case "hw capabilities":var c=await Pm3ReadOnlyInspector.QueryCapabilitiesAsync(t);_transport.Text=$"USB / Serial ACTIVE · capabilities v{c.SchemaVersion}";_ble.Text="NOT ACTIVE · no BLE transport selected";_wifi.Text="NOT ACTIVE · no Wi-Fi transport selected";_bwm.Text=$"Capabilities v{c.SchemaVersion} · BigBuf {c.BigBufferSize} bytes";Log(_consoleLog,$"CMD_CAPABILITIES schema v{c.SchemaVersion}; known={c.IsKnownSchema}; USB={(c.ViaUsb?"yes":"no")}; FPC={(c.ViaFpc?"yes":"no")}; baud={c.BaudRate}; BigBuf={c.BigBufferSize} bytes.");Log(_consoleLog,$"Enabled: {string.Join(", ",c.EnabledFeatures)}");Log(_diagLog,$"CAPABILITIES RAW: {Convert.ToHexString(c.RawPayload)}");break;case "hw status":var s=await Pm3ReadOnlyInspector.QueryStatusAsync(t);Log(_consoleLog,$"CMD_STATUS: {(s.Success?"OK":"FAILED")} (status={s.Status}, reason={s.Reason}, payload={s.PayloadLength} bytes)");var lines=DecodeDebugText(s.DebugFrames);if(lines.Count>0){Log(_consoleLog,$"hw status text: {lines.Count} lines received");foreach(var line in lines)Log(_consoleLog,$"  {line}");}foreach(var f in s.DebugFrames)Log(_diagLog,$"Interleaved 0x{f.Command:X4}: status={f.Status}, reason={f.Reason}, payload={f.Payload.Length} bytes, raw={Convert.ToHexString(f.Payload)}");break;case "hw ping":var q=await Pm3ReadOnlyInspector.PingAsync(t);Log(_consoleLog,$"CMD_PING: {(q.Success?"OK":"FAILED")} (status={q.Status}, reason={q.Reason}, payload={q.PayloadLength} bytes)");break;}});}
    private static IReadOnlyList<string> DecodeDebugText(IEnumerable<Pm3NgResponse> frames){var result=new List<string>();foreach(var f in frames.Where(x=>x.Command==0x0100)){var data=f.Payload;var start=(data.Length>=2&&data[0]==0x01&&data[1]==0x00)?2:0;if(start>=data.Length)continue;var text=Encoding.UTF8.GetString(data,start,data.Length-start).Replace("\0",string.Empty);text=Regex.Replace(text,"\\x1B\\[[0-9;]*m",string.Empty);text=text.Trim();if(!string.IsNullOrWhiteSpace(text))result.Add(text);}return result;}
    private async Task RunAsync(string label,Func<Pm3SerialTransport,Task> action){if(_busy||string.IsNullOrWhiteSpace(_port))return;_busy=true;_cts=new CancellationTokenSource();_execute.Enabled=false;_cancel.Enabled=true;_analyze.Enabled=false;Log(_consoleLog,$"--- {label} ---");await using var t=new Pm3SerialTransport(_port);try{await t.ConnectAsync();await action(t);_transport.Text="USB/Serial transaction OK";}catch(OperationCanceledException){Log(_consoleLog,$"{label}: CANCELLED");}catch(Exception ex){_transport.Text="Transaction failed";Log(_consoleLog,$"{label} failed: {ex.Message}");}finally{_cts.Dispose();_cts=null;_busy=false;_execute.Enabled=true;_cancel.Enabled=false;_analyze.Enabled=true;}}
    private void CancelCurrent(){_cts?.Cancel();Log(_diagLog,"Cancel requested. Transport cancellation will be applied by the active operation if supported.");}
    private bool TryGetPort(){RefreshPorts();if(!string.IsNullOrWhiteSpace(_port))return true;Log(_consoleLog,"No Windows serial port detected.");return false;}
    private void RefreshPorts(){var ports=GetSerialPorts();_port=ports.FirstOrDefault(p=>p.Equals("COM3",StringComparison.OrdinalIgnoreCase))??ports.FirstOrDefault();_usb.Text=_port is null?"Not detected":$"Detected · {_port}";_transport.Text=_port is null?"No USB serial transport":"USB serial endpoint detected";_ble.Text="NOT ACTIVE · not queried";_wifi.Text="NOT ACTIVE · not queried";}
    private static IReadOnlyList<string> GetSerialPorts(){var r=new List<string>();using var k=Registry.LocalMachine.OpenSubKey(@"HARDWARE\DEVICEMAP\SERIALCOMM");if(k is null)return r;foreach(var n in k.GetValueNames())if(k.GetValue(n) is string p&&!string.IsNullOrWhiteSpace(p))r.Add(p);return r.OrderBy(x=>x,StringComparer.OrdinalIgnoreCase).ToArray();}
    private void Log(TextBox b,string m){b.AppendText($"[{DateTime.Now:HH:mm:ss}] {m}{Environment.NewLine}");}
}
